#!/bin/sh
MYPATH="`dirname \"$0\"`"
SYSROOT="`realpath \"$MYPATH/waterbox-sysroot\"`"
export LDFLAGS=--target=pe-x86-64
export CFLAGS=-Werror
./configure --target=waterbox --build=waterbox --disable-shared --prefix="$SYSROOT" --syslibdir="$SYSROOT/syslib"
