#!/bin/sh
MYPATH="`dirname \"$0\"`"
SYSROOT="`realpath \"$MYPATH/waterbox-sysroot\"`"
export LDFLAGS=""
export CFLAGS="-Werror -mabi=ms -fPIE -fvisibility=hidden -mcmodel=large"
./configure --target=waterbox --build=waterbox --disable-shared --prefix="$SYSROOT" --syslibdir="$SYSROOT/syslib"
